# .github/workflows/deploy.yml
name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images
      run: |
        docker build -f docker/backend.Dockerfile -t gensamaa/backend .
        docker tag gensamaa/backend gensamaa/backend:latest
        docker push gensamaa/backend:latest
